# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-05 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasif_mat', '0005_auto_20180826_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='continente',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Seleccionar'), (1, 'Libro'), (2, 'Perforado'), (3, 'Anillado')], default=0),
        ),
        migrations.AddField(
            model_name='registro',
            name='estado_conservacion',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Seleccionar'), (1, 'Malo'), (2, 'Regular'), (3, 'Bueno'), (4, 'Muy bueno'), (5, 'Excelente')], default=0),
        ),
        migrations.AddField(
            model_name='registro',
            name='estado_escaneo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Seleccionar'), (1, 'Completo'), (2, 'Incompleto')], default=0),
        ),
        migrations.AddField(
            model_name='registro',
            name='observaciones',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
