# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasif_mat', '0006_auto_20180905_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='caja',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='registro',
            name='estante',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0),
        ),
        migrations.AlterField(
            model_name='registro',
            name='anio',
            field=models.PositiveSmallIntegerField(choices=[(1930, 1930), (1931, 1931), (1932, 1932), (1933, 1933), (1934, 1934), (1935, 1935), (1936, 1936), (1937, 1937), (1938, 1938), (1939, 1939), (1940, 1940), (1941, 1941), (1942, 1942), (1943, 1943), (1944, 1944), (1945, 1945), (1946, 1946), (1947, 1947), (1948, 1948), (1949, 1949), (1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999)]),
        ),
        migrations.AlterField(
            model_name='registro',
            name='archivo',
            field=models.FileField(default='', upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='contenido',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='registro',
            name='continente',
            field=models.PositiveSmallIntegerField(choices=[(None, 'Seleccionar'), (1, 'Libro o encuadernado'), (2, 'Perforado o carpeta de cartulina'), (3, 'Anillado')], default=0),
        ),
        migrations.AlterField(
            model_name='registro',
            name='estado_conservacion',
            field=models.PositiveSmallIntegerField(choices=[(None, 'Seleccionar'), (1, 'Malo'), (2, 'Regular'), (3, 'Bueno'), (4, 'Muy bueno'), (5, 'Excelente')], default=0),
        ),
        migrations.AlterField(
            model_name='registro',
            name='estado_escaneo',
            field=models.PositiveSmallIntegerField(choices=[(None, 'Seleccionar'), (1, 'Completo'), (2, 'Incompleto')], default=0),
        ),
        migrations.AlterField(
            model_name='registro',
            name='observaciones',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
