# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-06 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasif_mat', '0007_auto_20180906_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='continente',
            field=models.CharField(choices=[(None, 'Seleccionar'), ('Libro', 'Libro o encuadernado'), ('Perforado', 'Perforado o carpeta de cartulina'), ('Anillado', 'Anillado')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='registro',
            name='estado_conservacion',
            field=models.CharField(choices=[(None, 'Seleccionar'), ('Malo', 'Malo'), ('Regular', 'Regular'), ('Bueno', 'Bueno'), ('Muy bueno', 'Muy bueno'), ('Excelente', 'Excelente')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='registro',
            name='estado_escaneo',
            field=models.CharField(choices=[(None, 'Seleccionar'), ('Completo', 'Completo'), ('Incompleto', 'Incompleto')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='registro',
            name='estante',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0),
        ),
    ]
